name: Deploy Standing Together Project

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # ---------- Backend ----------

      - name: Install backend dependencies
        run: npm install
        working-directory: backend

      - name: Run Tests (Jest)
        run: npm test
        working-directory: backend

      - name: Build backend
        run: npm run build
        working-directory: backend

      # ---------- Frontend ----------

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

      # ---------- Restart ----------

      - name: Restart backend
        run: |
          pm2 restart standing-together-backend || pm2 start /home/runner/actions-runner/_work/Standing-together-2/Standing-together-2/backend/dist/index.js --name standing-together-backend
